name: cosmopipe
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _r-mutex
  - astropy
  - attrs
  - binutils
  - brotli
  - brotli-bin
  - brotlipy
  - bwidget
  - bzip2
  - c-ares
  - c-compiler
  - ca-certificates
  - cairo
  - camb
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - colorama
  - compilers
  - contourpy
  - cosmosis
  - cosmosis-build-standard-library
  - cryptography
  - curl
  - cxx-compiler
  - cycler
  - dulwich
  - dynesty
  - emcee
  - exceptiongroup
  - expat
  - fast-pt
  - fftw
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fortran-compiler
  - freetype
  - fribidi
  - future
  - gettext
  - gfortran
  - git
  - gmp
  - gmpy2
  - graphite2
  - gsl
  - harfbuzz
  - icu
  - idna
  - importlib-metadata
  - importlib-resources
  - importlib_resources
  - iniconfig
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libsqlite
  - libssh2
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - make
  - matplotlib-base
  - minuit2_standalone
  - mock
  - mpc
  - mpfr
  - mpi
  - mpi4py
  - mpich
  - mpich-mpicc
  - mpmath
  - munkres
  - nautilus-sampler
  - ncurses
  - openjpeg
  - openlibm
  - openmp
  - openssl
  - packaging
  - pandas
  - pango
  - patsy
  - pcre2
  - perl
  - pillow
  - pip
  - pixman
  - platformdirs
  - pluggy
  - pooch
  - pthread-stubs
  - pybind11
  - pybind11-global
  - pycparser
  - pyerfa
  - pyopenssl
  - pyparsing
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - r
  - r-base
  - r-boot
  - r-class
  - r-cluster
  - r-codetools
  - r-foreign
  - r-kernsmooth
  - r-lattice
  - r-mass
  - r-matrix
  - r-mgcv
  - r-nlme
  - r-nnet
  - r-recommended
  - r-remotes
  - r-rpart
  - r-spatial
  - r-survival
  - readline
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - sed
  - setuptools
  - six
  - statsmodels
  - sympy
  - threadpoolctl
  - tk
  - tktable
  - tomli
  - tqdm
  - typing-extensions
  - typing_extensions
  - unicodedata2
  - urllib3
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeus-mcmc
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - astropandas==1.1.3
    - cachetools==5.3.0
    - cloudpickle==2.2.1
    - cosmopower==0.1.3
    - cython==0.29.34
    - d2to1==0.2.12.post1
    - decorator==5.1.1
    - dm-tree==0.1.8
    - fitsio==1.1.1
    - flatbuffers==23.3.3
    - gast==0.4.0
    - google-auth==2.17.1
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.53.0
    - h5py==3.8.0
    - jax==0.4.8
    - keras==2.12.0
    - libclang==16.0.0
    - lsstdesc-coord==1.2.3
    - markdown==3.4.3
    - markupsafe==2.1.2
    - ml-dtypes==0.0.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - palettable==3.3.0
    - protobuf==4.22.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytest-runner==6.0.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tabeval @ git+https://github.com/jlvdb/tabeval.git
    - tensorboard==2.12.1
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - tensorflow-probability==0.19.0
    - termcolor==2.2.0
    - treecorr==4.2.3
    - werkzeug==2.2.3
    - wrapt==1.14.1
