name: cosmopipe
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - cosmosis=2.3.2
  - cosmosis-build-standard-library
  - numpy<1.24
  - r=4.1
  - pip:
    - astropandas
    - cosmopower
    - cython
    - numpy
    - tabeval @ git+https://github.com/jlvdb/tabeval.git
    - treecorr
