name: cosmopipe
channels:
  - conda-forge
  - defaults
dependencies:
  - camb
  - cosmosis
  - cosmosis-build-standard-library
  - emcee
  - nautilus-sampler
  - python=3.8
  - pip
  - r=4.1
  - pip:
    - astropandas
    - cosmopower
    - cython
    - numpy
    - tabeval @ git+https://github.com/jlvdb/tabeval.git
    - treecorr
